title: <b>Rezaul Karim, Ph.D.</b>
url: "rezacsedu.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://www.linkedin.com/in/karimanalytics/"
footer_text: "&copy;2026 Rezaul Karim, Ph.D."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "Resume"
   link: "cv.pdf"
 - name: "Awards"
   link: "awards"
 - name: "Books"
   link: "books"
 - name: "Teaching"
   link: "teaching"
 - name: "Certifications"
   link: "certifications"
 - name: "Talks"
   link: "talks"
 # - name: "Projects"
 #   link: "projects"
 - name: "Training"
   link: "training"
 - name: "Reviews"
   link: "reviews"
 - name: "Contact"
   link: "contact"
